---
apiVersion: v1
kind: Namespace
metadata:
  name: sc4s
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-credential
  namespace: sc4s
type: Opaque
data:
  password: Q2hhbmdlZCE=
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer