---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc4s-local-pvc
  namespace: sc4s
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sc4s-local-pv
  selector:
    matchLabels: 
      name: sc4s-local-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssc4s-local-pv
  namespace: sc4s
  labels:
    type: local
    name: sc4s-local-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s/sc4s_local"